## Testing One

First dataset on anger.

In [2]:
# import libraries needed for the dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import sklearn.preprocessing as pp

In [22]:
from pathlib import Path

csv_name = "Do We Mean It, or Just Say It Wrong.csv"
csv_path = Path.cwd() / csv_name
if not csv_path.is_file():
    csv_path = Path.home() / "Downloads" / "Emotions" / csv_name

anger = pd.read_csv(csv_path)
anger.head()

,Timestamp,"When you become angry during a conversation, how do you usually react?",What type of conversations or situations are most likely to trigger your anger?,How do you usually handle your anger after the conversation?,"When you say things while angry, do you usually mean them?","If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?","If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express?",Do you think anger changes:,"After calming down, how often do you feel your words came out harsher than intended?"
0,27/05/2026 22:16:27,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,27/05/2026 22:28:32,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,27/05/2026 22:33:00,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,27/05/2026 22:36:28,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,27/05/2026 22:42:38,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes

In [23]:
import functions as f
# Dropping the Timestamp column as it is not needed for analysis
anger.drop(columns=['Timestamp'], inplace=True)

anger.head(10)

,"When you become angry during a conversation, how do you usually react?",What type of conversations or situations are most likely to trigger your anger?,How do you usually handle your anger after the conversation?,"When you say things while angry, do you usually mean them?","If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?","If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express?",Do you think anger changes:,"After calming down, how often do you feel your words came out harsher than intended?"
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,NaN,How people express what they feel?,Always

In [24]:
# Changing column names
anger.rename(columns={
    'When you become angry during a conversation, how do you usually react?': 'Reaction',
    'What type of conversations or situations are most likely to trigger your anger? ': 'Trigger',
    'How do you usually handle your anger after the conversation? ': 'Handling',
    'When you say things while angry, do you usually mean them? ': 'Meaning',
    'If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?': 'Better_Way',
    'If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express? ': 'Ways_to_Express',
    'After calming down, how often do you feel your words came out harsher than intended? ': 'Reflection',
    '    Do you think anger changes:': 'Anger_Changes',
}, inplace=True)

anger.head(10)

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,NaN,How people express what they feel?,Always

# Data Dictionary

- `When you ecome angry during a conversation, how do you usually react?` - `Reaction`
  
- `What type of conversations or situations are most likely to trigger your anger?` - `Trigger`
  
- `How do you usually handle your anger after the conversation?` - `Handling`
  
- `When you say things while angry, do you usually mean them?` - `Meaning`
  
- `If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?` - `Better_Way`
  
- `If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express? ` - `Ways_to_Express`
  
- `After calming down, how often do you feel your words came out harsher than intended? ` - `Reflection`

# Data Cleaning and Preprocessing

In [25]:
# Data Cleaning and Preprocessing
f.find_nan(anger,'Ways_to_Express')
anger['Ways_to_Express'].fillna('Not applicable', inplace=True)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,Not applicable,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,Not applicable,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,Not applicable,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,Not applicable,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,Not applicable,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,Not applicable,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,Sometimes,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Sometimes,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,Partly,Maybe,Not applicable,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,Sometimes,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,"Yes, completely",No,Not applicable,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,"No, not really",Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,Sometimes,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,Partly,Yes,Not applicable,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,Sometimes,Yes,Not applicable,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,Partly,Yes,Not applicable,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,Rarely,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,Sometimes,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,Sometimes,Yes,Not applicable,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,Partly,Yes,Not applicable,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,Sometimes,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,Partly,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,"Yes, completely",NaN,Not applicable,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,"Yes, completely",Yes,Not applicable,Both?,Always
29,I become quiet and withdraw,NaN,I avoid the person for some time,Partly,Yes,Not applicable,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,"Yes, completely",No,Not applicable,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,Sometimes,Yes,Not applicable,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,Partly,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,Partly,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,Partly,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,"Yes, completely",Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,"No, not really",Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,"Yes, completely",Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,Sometimes,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,"No, not really",NaN,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,"Yes, completely",Yes,Not applicable,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,"Yes, completely",No,Not applicable,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,"Yes, completely",No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,Rarely,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,Not applicable,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,Partly,Yes,Not applicable,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",Partly,Maybe,Not applicable,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,Partly,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,Partly,Maybe,Not applicable,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,Rarely,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,Partly,Yes,Not applicable,Both?,Often

In [26]:
# Encoding
categories= [['No, not really','Yes, completely','Sometimes','Partly','Rarely']]
encoder= pp.OrdinalEncoder(categories=categories, dtype=int)
# Map the text responses to ordered numeric values before casting
meaning_map = {
    'No, not really': 0,
    'Yes, completely': 1,
    'Sometimes': 2,
    'Partly': 3,
    'Rarely': 4
}

anger['Meaning'] = anger['Meaning'].apply(
    lambda x: meaning_map.get(str(x).strip(), x)
).astype(int)

anger['Meaning'] = encoded.astype(int)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,Not applicable,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,Not applicable,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,Not applicable,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,Not applicable,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,Not applicable,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,Not applicable,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,Not applicable,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,Not applicable,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,Not applicable,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,Not applicable,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,NaN,Not applicable,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,Not applicable,Both?,Always
29,I become quiet and withdraw,NaN,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,Not applicable,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,Not applicable,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,NaN,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,Not applicable,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,Not applicable,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,Not applicable,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,Not applicable,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,Not applicable,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,Not applicable,Both?,Often

In [27]:
anger['Better_Way'].fillna('Not applicable', inplace=True)
anger['Trigger'].fillna('Feeling disrespected', inplace= True)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,Not applicable,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,Not applicable,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,Not applicable,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,Not applicable,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,Not applicable,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,Not applicable,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,Not applicable,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,Not applicable,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,Not applicable,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,Not applicable,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,Not applicable,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,Not applicable,Not applicable,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,Not applicable,Both?,Always
29,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,Not applicable,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,Not applicable,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,Not applicable,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,Not applicable,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,Not applicable,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,Not applicable,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,Not applicable,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,Not applicable,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,Not applicable,Both?,Often

In [28]:
category= [['Never','Rarely','Sometimes','Often','Always']]
enc=pp.OrdinalEncoder(categories=category, dtype=int)
encd= enc.fit_transform(anger[['Reflection']])

anger['Reflection'] = encd.astype(int)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,Not applicable,Yes,Both?,2
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,Not applicable,Neither?,3
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,4
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Both?,3
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,Not applicable,How people express what they feel?,2
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,Not applicable,How people express what they feel?,2
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,Not applicable,Both?,4
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,2
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,3
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,4
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,3
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,3
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,Not applicable,Both?,2
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,2
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,Not applicable,How people express what they feel?,1
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,4
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,1
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,Not applicable,How people express what they feel?,3
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,Not applicable,How people express what they feel?,2
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,How people express what they feel?,2
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,3
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,4
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,Not applicable,How people express what they feel?,2
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,Not applicable,Both?,2
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,4
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,4
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,2
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,Not applicable,Not applicable,Both?,3
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,Not applicable,Both?,4
29,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,3
30,It depends,Feeling ignored,I regret some of my words,1,No,Not applicable,Both?,0
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,Not applicable,Both?,3
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,4
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,1
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,4
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,1
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,4
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,2
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,1
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,Not applicable,Yes,How people express what they feel?,2
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,Not applicable,Both?,1
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,Not applicable,How people express what they feel?,1
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,1
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,3
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,3
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,1
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,Not applicable,How people express what they feel?,4
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,Not applicable,How people express what they feel?,2
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,4
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,Not applicable,How people express what they feel?,2
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,3
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,Not applicable,Both?,3

In [29]:
# Creating function for encoding
def encode(df, column_name, categories):
    """
    Encodes a categorical column in the DataFrame using Ordinal Encoding.

    Parameters:
    df (pd.DataFrame): The DataFrame containing the column to encode.
    column_name (str): The name of the column to encode.
    categories (list): A list of lists specifying the order of categories.

    Returns:
    pd.DataFrame: The DataFrame with the encoded column.
    """
    encoder = pp.OrdinalEncoder(categories=categories, dtype=int)
    encoded = encoder.fit_transform(df[[column_name]])
    df[column_name] = encoded.astype(int)
    return df

In [30]:
encode(anger, 'Better_Way', [['Not applicable','No','Maybe','Yes']])
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,0,Yes,Both?,2
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,3,Not applicable,Neither?,3
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,3,Yes,What people truly feel?,4
3,It depends,Repetition/frustration,I reflect on what was said,3,3,Not applicable,Both?,3
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,2,Not applicable,How people express what they feel?,2
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,3,Not applicable,How people express what they feel?,2
6,I raise my voice,Being misunderstood,I apologise if necessary,3,0,Not applicable,Both?,4
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,2,No,How people express what they feel?,2
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,3,Yes,Both?,3
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,3,Not applicable,How people express what they feel?,4
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,3,Yes,Both?,3
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,0,No,Both?,3
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,2,Not applicable,Both?,2
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,2,Maybe,How people express what they feel?,2
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,1,Not applicable,How people express what they feel?,1
15,It depends,Dishonesty or lies,I regret some of my words,0,0,Yes,Both?,4
16,It depends,Feeling disrespected,I apologise if necessary,2,3,Yes,Both?,1
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,3,Not applicable,How people express what they feel?,3
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,3,Not applicable,How people express what they feel?,2
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,3,Not applicable,How people express what they feel?,2
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,0,Yes,Both?,3
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,3,Maybe,How people express what they feel?,4
22,It depends,Dishonesty or lies,I apologise if necessary,2,3,Not applicable,How people express what they feel?,2
23,It depends,Disrespecting my parents,I reflect on what was said,3,3,Not applicable,Both?,2
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,2,No,How people express what they feel?,4
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,3,No,Both?,4
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,2,No,How people express what they feel?,2
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,0,Not applicable,Both?,3
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,3,Not applicable,Both?,4
29,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,3,Not applicable,How people express what they feel?,3
30,It depends,Feeling ignored,I regret some of my words,1,1,Not applicable,Both?,0
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,3,Not applicable,Both?,3
32,It depends,Feeling disrespected,I reflect on what was said,3,1,No,How people express what they feel?,4
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,0,Yes,How people express what they feel?,1
34,It depends,Feeling disrespected,I reflect on what was said,3,3,Maybe,How people express what they feel?,4
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,2,No,Both?,1
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,0,Yes,How people express what they feel?,4
37,I raise my voice,all except lies,I apologise if necessary,1,0,No,How people express what they feel?,2
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,3,Maybe,How people express what they feel?,1
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,0,Yes,How people express what they feel?,2
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,3,Not applicable,Both?,1
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,1,Not applicable,How people express what they feel?,1
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,1,No,How people express what they feel?,1
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,1,No,Neither?,3
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,2,No,Both?,3
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,3,Not applicable,How people express what they feel?,1
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,3,Not applicable,How people express what they feel?,4
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,2,Not applicable,How people express what they feel?,2
48,It depends,Dishonesty or lies,I regret some of my words,3,2,Yes,What people truly feel?,4
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,2,Not applicable,How people express what they feel?,2
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,0,Yes,Both?,3
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,3,Not applicable,Both?,3

In [32]:
#encode(anger,'Ways_to_Express', [['Not applicable','No','Maybe','Yes']])
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,0,3,Both?,2
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,3,0,Neither?,3
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,3,3,What people truly feel?,4
3,It depends,Repetition/frustration,I reflect on what was said,3,3,0,Both?,3
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,2,0,How people express what they feel?,2
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,3,0,How people express what they feel?,2
6,I raise my voice,Being misunderstood,I apologise if necessary,3,0,0,Both?,4
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,2,1,How people express what they feel?,2
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,3,3,Both?,3
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,3,0,How people express what they feel?,4
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,3,3,Both?,3
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,0,1,Both?,3
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,2,0,Both?,2
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,2,2,How people express what they feel?,2
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,1,0,How people express what they feel?,1
15,It depends,Dishonesty or lies,I regret some of my words,0,0,3,Both?,4
16,It depends,Feeling disrespected,I apologise if necessary,2,3,3,Both?,1
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,3,0,How people express what they feel?,3
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,3,0,How people express what they feel?,2
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,3,0,How people express what they feel?,2
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,0,3,Both?,3
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,3,2,How people express what they feel?,4
22,It depends,Dishonesty or lies,I apologise if necessary,2,3,0,How people express what they feel?,2
23,It depends,Disrespecting my parents,I reflect on what was said,3,3,0,Both?,2
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,2,1,How people express what they feel?,4
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,3,1,Both?,4
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,2,1,How people express what they feel?,2
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,0,0,Both?,3
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,3,0,Both?,4
29,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,3,0,How people express what they feel?,3
30,It depends,Feeling ignored,I regret some of my words,1,1,0,Both?,0
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,3,0,Both?,3
32,It depends,Feeling disrespected,I reflect on what was said,3,1,1,How people express what they feel?,4
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,0,3,How people express what they feel?,1
34,It depends,Feeling disrespected,I reflect on what was said,3,3,2,How people express what they feel?,4
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,2,1,Both?,1
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,0,3,How people express what they feel?,4
37,I raise my voice,all except lies,I apologise if necessary,1,0,1,How people express what they feel?,2
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,3,2,How people express what they feel?,1
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,0,3,How people express what they feel?,2
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,3,0,Both?,1
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,1,0,How people express what they feel?,1
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,1,1,How people express what they feel?,1
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,1,1,Neither?,3
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,2,1,Both?,3
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,3,0,How people express what they feel?,1
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,3,0,How people express what they feel?,4
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,2,0,How people express what they feel?,2
48,It depends,Dishonesty or lies,I regret some of my words,3,2,3,What people truly feel?,4
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,2,0,How people express what they feel?,2
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,0,3,Both?,3
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,3,0,Both?,3

In [33]:
pd.get_dummies(anger, columns=['Reaction', 'Trigger', 'Handling'], drop_first=True)

,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection,Reaction_I avoid the conversation entirely,Reaction_I become quiet and withdraw,Reaction_I cry,Reaction_I raise my voice,Reaction_I say things impulsively,...,Trigger_all except lies,Handling_I avoid the person for some time,Handling_I calm down quickly,Handling_I leave the scene to think things through,Handling_I reflect on what I did if I was wrong I apologise and also tell them Thier faults during conversations most time both sides have a truth in whatever they say so we Check ans explain calmly or loudly but if loudly we laugh over it,Handling_I reflect on what was said,Handling_I regret some of my words,"Handling_More than one option acc option. 2, 3, 4 and depending 6",Handling_Omoo,"Handling_Sometimes I cry too, anger is a painful emotion"
0,0,0,3,Both?,2,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,3,3,0,Neither?,3,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,1,3,3,What people truly feel?,4,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,3,0,Both?,3,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
4,2,2,0,How people express what they feel?,2,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
5,2,3,0,How people express what they feel?,2,False,False,False,True,False,...,False,True,False,False,False,False,False,False,False,False
6,3,0,0,Both?,4,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
7,1,2,1,How people express what they feel?,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,3,3,3,Both?,3,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
9,3,3,0,How people express what they feel?,4,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
10,2,3,3,Both?,3,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
11,2,0,1,Both?,3,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
12,3,2,0,Both?,2,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13,2,2,2,How people express what they feel?,2,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
14,1,1,0,How people express what they feel?,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,0,0,3,Both?,4,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
16,2,3,3,Both?,1,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,3,3,0,How people express what they feel?,3,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
18,2,3,0,How people express what they feel?,2,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
19,3,3,0,How people express what they feel?,2,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
20,4,0,3,Both?,3,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
21,2,3,2,How people express what they feel?,4,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
22,2,3,0,How people express what they feel?,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,3,3,0,Both?,2,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
24,2,2,1,How people express what they feel?,4,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
25,3,3,1,Both?,4,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,3,2,1,How people express what they feel?,2,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
27,1,0,0,Both?,3,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
28,1,3,0,Both?,4,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
29,3,3,0,How people express what they feel?,3,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
30,1,1,0,Both?,0,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
31,2,3,0,Both?,3,False,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
32,3,1,1,How people express what they feel?,4,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
33,3,0,3,How people express what they feel?,1,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
34,3,3,2,How people express what they feel?,4,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
35,1,2,1,Both?,1,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
36,0,0,3,How people express what they feel?,4,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
37,1,0,1,How people express what they feel?,2,False,False,False,True,False,...,True,False,False,False,False,False,False,False,False,False
38,2,3,2,How people express what they feel?,1,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,0,0,3,How people express what they feel?,2,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
40,1,3,0,Both?,1,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
41,1,1,0,How people express what they feel?,1,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
42,1,1,1,How people express what they feel?,1,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43,1,1,1,Neither?,3,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
44,4,2,1,Both?,3,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
45,3,3,0,How people express what they feel?,1,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
46,3,3,0,How people express what they feel?,4,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
47,3,2,0,How people express what they feel?,2,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
48,3,2,3,What people truly feel?,4,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
49,3,2,0,How people express what they feel?,2,False,False,False,False,True,...,False,True,False,False,False,False,False,False,False,False
50,4,0,3,Both?,3,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
51,3,3,0,Both?,3,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False