## Testing One

First dataset on anger.

In [37]:
# import libraries needed for the dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import sklearn.preprocessing as pp

In [47]:
from pathlib import Path

csv_name = "Do We Mean It, or Just Say It Wrong.csv"
csv_path = Path.cwd() / csv_name
if not csv_path.is_file():
    csv_path = Path.home() / "Downloads" / "Emotions" / csv_name

anger = pd.read_csv(csv_path)
anger.head()

,Timestamp,"When you become angry during a conversation, how do you usually react?",What type of conversations or situations are most likely to trigger your anger?,How do you usually handle your anger after the conversation?,"When you say things while angry, do you usually mean them?","If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?","If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express?",Do you think anger changes:,"After calming down, how often do you feel your words came out harsher than intended?"
0,27/05/2026 22:16:27,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,27/05/2026 22:28:32,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,27/05/2026 22:33:00,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,27/05/2026 22:36:28,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,27/05/2026 22:42:38,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes

In [48]:
import functions as f
# Dropping the Timestamp column as it is not needed for analysis
anger.drop(columns=['Timestamp'], inplace=True)

anger.head(10)

,"When you become angry during a conversation, how do you usually react?",What type of conversations or situations are most likely to trigger your anger?,How do you usually handle your anger after the conversation?,"When you say things while angry, do you usually mean them?","If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?","If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express?",Do you think anger changes:,"After calming down, how often do you feel your words came out harsher than intended?"
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,NaN,How people express what they feel?,Always

In [50]:
# Changing column names
anger.rename(columns={
    'When you become angry during a conversation, how do you usually react?': 'Reaction',
    'What type of conversations or situations are most likely to trigger your anger? ': 'Trigger',
    'How do you usually handle your anger after the conversation? ': 'Handling',
    'When you say things while angry, do you usually mean them? ': 'Meaning',
    'If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?': 'Better_Way',
    'If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express? ': 'Ways_to_Express',
    'After calming down, how often do you feel your words came out harsher than intended? ': 'Reflection',
    '    Do you think anger changes:': 'Anger_Changes',
}, inplace=True)

anger.head(10)

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,NaN,How people express what they feel?,Always

# Data Dictionary

- `When you ecome angry during a conversation, how do you usually react?` - `Reaction`
  
- `What type of conversations or situations are most likely to trigger your anger?` - `Trigger`
  
- `How do you usually handle your anger after the conversation?` - `Handling`
  
- `When you say things while angry, do you usually mean them?` - `Meaning`
  
- `If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?` - `Better_Way`
  
- `If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express? ` - `Ways_to_Express`
  
- `After calming down, how often do you feel your words came out harsher than intended? ` - `Reflection`

# Data Cleaning and Preprocessing

In [52]:
# Data Cleaning and Preprocessing
f.find_nan(anger,'Ways_to_Express')

#anger

np.int64(25)

In [53]:
# Encoding
categories= [['No, not really','Yes, completely','Sometimes','Partly','Rarely']]
encoder= pp.OrdinalEncoder(categories=categories, dtype=int)
encoded= encoder.fit_transform(anger[['Meaning']])

anger['Meaning'] = encoded.astype(int)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,NaN,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,NaN,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,NaN,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,NaN,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,NaN,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,NaN,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,NaN,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,NaN,NaN,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,NaN,Both?,Always
29,I become quiet and withdraw,NaN,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,NaN,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,NaN,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,NaN,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,NaN,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,NaN,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,NaN,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,NaN,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,NaN,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,NaN,Both?,Often

In [ ]:
anger['Better_Way'].fillna('Not applicable', inplace=True)
anger['Trigger'].fillna('Feeling disrespected', inplace= True)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,Not applicable,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,NaN,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,NaN,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,NaN,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,NaN,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,NaN,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,NaN,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,NaN,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,Not applicable,NaN,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,NaN,Both?,Always
29,I become quiet and withdraw,NaN,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,NaN,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,NaN,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,Not applicable,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,NaN,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,NaN,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,NaN,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,NaN,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,NaN,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,NaN,Both?,Often

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
count,52,51,52,52.000000,52,27,52,52
unique,10,13,10,NaN,4,3,4,5
top,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,NaN,Yes,Yes,How people express what they feel?,Sometimes
freq,19,15,13,NaN,24,12,27,15
mean,NaN,NaN,NaN,2.134615,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.085174,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN