## Testing One

First dataset on anger.

In [149]:
# import libraries needed for the dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import sklearn.preprocessing as pp

In [150]:
from pathlib import Path

csv_name = "Do We Mean It, or Just Say It Wrong.csv"
csv_path = Path.cwd() / csv_name
if not csv_path.is_file():
    csv_path = Path.home() / "Downloads" / "Emotions" / csv_name

anger = pd.read_csv(csv_path)
anger.head()

,Timestamp,"When you become angry during a conversation, how do you usually react?",What type of conversations or situations are most likely to trigger your anger?,How do you usually handle your anger after the conversation?,"When you say things while angry, do you usually mean them?","If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?","If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express?",Do you think anger changes:,"After calming down, how often do you feel your words came out harsher than intended?"
0,27/05/2026 22:16:27,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,27/05/2026 22:28:32,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,27/05/2026 22:33:00,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,27/05/2026 22:36:28,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,27/05/2026 22:42:38,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes

In [151]:
import functions as f
# Dropping the Timestamp column as it is not needed for analysis
anger.drop(columns=['Timestamp'], inplace=True)

anger.head(10)

,"When you become angry during a conversation, how do you usually react?",What type of conversations or situations are most likely to trigger your anger?,How do you usually handle your anger after the conversation?,"When you say things while angry, do you usually mean them?","If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?","If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express?",Do you think anger changes:,"After calming down, how often do you feel your words came out harsher than intended?"
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,NaN,How people express what they feel?,Always

In [152]:
# Changing column names
anger.rename(columns={
    'When you become angry during a conversation, how do you usually react?': 'Reaction',
    'What type of conversations or situations are most likely to trigger your anger? ': 'Trigger',
    'How do you usually handle your anger after the conversation? ': 'Handling',
    'When you say things while angry, do you usually mean them? ': 'Meaning',
    'If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?': 'Better_Way',
    'If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express? ': 'Ways_to_Express',
    'After calming down, how often do you feel your words came out harsher than intended? ': 'Reflection',
    '    Do you think anger changes:': 'Anger_Changes',
}, inplace=True)

anger.head(10)

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"No, not really",NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,Partly,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,"Yes, completely",Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,Partly,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,Sometimes,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,Sometimes,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,Partly,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,"Yes, completely",Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",Partly,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,Partly,Yes,NaN,How people express what they feel?,Always

# Data Dictionary

- `When you ecome angry during a conversation, how do you usually react?` - `Reaction`
  
- `What type of conversations or situations are most likely to trigger your anger?` - `Trigger`
  
- `How do you usually handle your anger after the conversation?` - `Handling`
  
- `When you say things while angry, do you usually mean them?` - `Meaning`
  
- `If you answered “Yes,” “Partly,” or “Sometimes,” do you think there could have been a better or calmer way to express what you meant?` - `Better_Way`
  
- `If you answered “Rarely” or “No,” do you think your anger caused you to say things you did not truly intend to express? ` - `Ways_to_Express`
  
- `After calming down, how often do you feel your words came out harsher than intended? ` - `Reflection`

# Data Cleaning and Preprocessing

In [153]:
# Data Cleaning and Preprocessing
f.find_nan(anger,'Ways_to_Express')

#anger

np.int64(25)

In [154]:
# Encoding
categories= [['No, not really','Yes, completely','Sometimes','Partly','Rarely']]
encoder= pp.OrdinalEncoder(categories=categories, dtype=int)
encoded= encoder.fit_transform(anger[['Meaning']])

anger['Meaning'] = encoded.astype(int)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,NaN,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,NaN,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,NaN,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,NaN,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,NaN,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,NaN,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,NaN,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,NaN,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,NaN,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,NaN,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,NaN,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,NaN,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,NaN,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,NaN,NaN,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,NaN,Both?,Always
29,I become quiet and withdraw,NaN,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,NaN,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,NaN,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,NaN,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,NaN,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,NaN,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,NaN,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,NaN,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,NaN,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,NaN,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,NaN,Both?,Often

In [155]:
anger['Better_Way'].fillna('Not applicable', inplace=True)
anger['Trigger'].fillna('Feeling disrespected', inplace= True)
anger['Ways_to_Express'].fillna('Not applicable', inplace=True)
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Anger_Changes,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,Not applicable,Yes,Both?,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,Not applicable,Neither?,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,What people truly feel?,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Both?,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,Not applicable,How people express what they feel?,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,Not applicable,How people express what they feel?,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,Not applicable,Both?,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,How people express what they feel?,Sometimes
8,I say things impulsively,Being misunderstood,"More than one option acc option. 2, 3, 4 and ...",3,Yes,Yes,Both?,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Both?,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Both?,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,Not applicable,Both?,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,How people express what they feel?,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,Not applicable,How people express what they feel?,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Both?,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Both?,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,Not applicable,How people express what they feel?,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,Not applicable,How people express what they feel?,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,How people express what they feel?,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Both?,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,Not applicable,How people express what they feel?,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,Not applicable,Both?,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,How people express what they feel?,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Both?,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,How people express what they feel?,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,Not applicable,Not applicable,Both?,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,Not applicable,Both?,Always
29,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,Not applicable,Both?,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,Not applicable,Both?,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,How people express what they feel?,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,How people express what they feel?,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,How people express what they feel?,Always
35,Be quiet and let them know Thier faults we ref...,"Lies , dishonesty, trying to act smart,critici...",I reflect on what I did if I was wrong I apolo...,1,Maybe,No,Both?,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,How people express what they feel?,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,How people express what they feel?,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,How people express what they feel?,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,Not applicable,Yes,How people express what they feel?,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,Not applicable,Both?,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,Not applicable,How people express what they feel?,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,How people express what they feel?,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Neither?,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Both?,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,How people express what they feel?,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,Not applicable,How people express what they feel?,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...","Sometimes I cry too, anger is a painful emotion",3,Maybe,Not applicable,How people express what they feel?,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,What people truly feel?,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,Not applicable,How people express what they feel?,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Both?,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,Not applicable,Both?,Often

In [156]:
anger.drop(columns='Anger_Changes',inplace=True)
anger.head()

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,Not applicable,Yes,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,Not applicable,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,Not applicable,Sometimes

In [157]:
anger['Trigger'] = anger['Trigger'].replace(
    'Lies , dishonesty, trying to act smart,criticism, betrayal ',
    'Lies, criticism, betrayal',
    regex=False
).str.strip()

anger['Trigger']= anger['Trigger'].replace(
    "Can't i pick two frustration, criticism, lies and being misunderstood",
    'Frustration, criticism, lies, being misunderstood',
    regex=False
).str.strip()

anger['Trigger']= anger['Trigger'].replace(
    "When i’m accused of something i didn’t do",
    'Accusations',
    regex=False
).str.strip()


anger['Handling'] = anger['Handling'].replace('More than one option acc  option. 2, 3, 4 and depending 6', 'Omoo', regex=False).str.strip()
anger['Handling']= anger['Handling'].replace('Sometimes I cry too, anger is a painful emotion', 'I cry',regex= False).str.strip()
anger['Handling']= anger['Handling'].replace(
    'I reflect on what I did if I was wrong I apologise and also tell them Thier faults during conversations most time both sides have a truth in whatever they say so we Check ans explain calmly or loudly but if loudly we laugh over it',
    'I reflect on my actions, apologise when wrong, and calmly or humorously discuss both sides faults, ' \
    'recognising that we may each have some truth.', regex= False
).str.strip()

In [158]:
anger

,Reaction,Trigger,Handling,Meaning,Better_Way,Ways_to_Express,Reflection
0,I become quiet and withdraw,Being misunderstood,I apologise if necessary,0,Not applicable,Yes,Sometimes
1,I become quiet and withdraw,Repetition/frustration,I regret some of my words,3,Yes,Not applicable,Often
2,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,Yes,Yes,Always
3,It depends,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Often
4,I become quiet and withdraw,Feeling ignored,I reflect on what was said,2,Maybe,Not applicable,Sometimes
5,I raise my voice,Feeling disrespected,I avoid the person for some time,2,Yes,Not applicable,Sometimes
6,I raise my voice,Being misunderstood,I apologise if necessary,3,Not applicable,Not applicable,Always
7,I try to explain my feelings calmly,Criticism,I apologise if necessary,1,Maybe,No,Sometimes
8,I say things impulsively,Being misunderstood,Omoo,3,Yes,Yes,Often
9,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,Always
10,I say things impulsively,Feeling disrespected,I leave the scene to think things through,2,Yes,Yes,Often
11,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,2,Not applicable,No,Often
12,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Maybe,Not applicable,Sometimes
13,I become quiet and withdraw,Being misunderstood,I avoid the person for some time,2,Maybe,Maybe,Sometimes
14,I try to explain my feelings calmly,Repetition/frustration,I apologise if necessary,1,No,Not applicable,Rarely
15,It depends,Dishonesty or lies,I regret some of my words,0,Not applicable,Yes,Always
16,It depends,Feeling disrespected,I apologise if necessary,2,Yes,Yes,Rarely
17,I cry,When I’m accused of something I didn’t do,I apologise if necessary,3,Yes,Not applicable,Often
18,I raise my voice,Dishonesty or lies,I regret some of my words,2,Yes,Not applicable,Sometimes
19,I become quiet and withdraw,Repetition/frustration,I reflect on what was said,3,Yes,Not applicable,Sometimes
20,It depends,Feeling disrespected and being gaslit,I reflect on what was said,4,Not applicable,Yes,Often
21,I say things impulsively,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,Always
22,It depends,Dishonesty or lies,I apologise if necessary,2,Yes,Not applicable,Sometimes
23,It depends,Disrespecting my parents,I reflect on what was said,3,Yes,Not applicable,Sometimes
24,I become quiet and withdraw,Being misunderstood,I reflect on what was said,2,Maybe,No,Always
25,It depends on the person if he/she is raising ...,Repetition/frustration,I apologise if necessary,3,Yes,No,Always
26,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Maybe,No,Sometimes
27,I become quiet and withdraw,Being misunderstood,I reflect on what was said,1,Not applicable,Not applicable,Often
28,I speak more emotionally/intensely,Feeling disrespected,I calm down quickly,1,Yes,Not applicable,Always
29,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,Often
30,It depends,Feeling ignored,I regret some of my words,1,No,Not applicable,Never
31,I become quiet and withdraw,Feeling disrespected,I reflect on what was said,2,Yes,Not applicable,Often
32,It depends,Feeling disrespected,I reflect on what was said,3,No,No,Always
33,I speak more emotionally/intensely,Being misunderstood,I reflect on what was said,3,Not applicable,Yes,Rarely
34,It depends,Feeling disrespected,I reflect on what was said,3,Yes,Maybe,Always
35,Be quiet and let them know Thier faults we ref...,"Lies, criticism, betrayal","I reflect on my actions, apologise when wrong,...",1,Maybe,No,Rarely
36,I avoid the conversation entirely,Feeling disrespected,I reflect on what was said,0,Not applicable,Yes,Always
37,I raise my voice,all except lies,I apologise if necessary,1,Not applicable,No,Sometimes
38,I become quiet and withdraw,Feeling disrespected,I apologise if necessary,2,Yes,Maybe,Rarely
39,I say things impulsively,Being misunderstood,I avoid the person for some time,0,Not applicable,Yes,Sometimes
40,I speak more emotionally/intensely,Being misunderstood,I calm down quickly,1,Yes,Not applicable,Rarely
41,I avoid the conversation entirely,Dishonesty or lies,Omoo,1,No,Not applicable,Rarely
42,I become quiet and withdraw,Being misunderstood,I apologise if necessary,1,No,No,Rarely
43,I become quiet and withdraw,Repetition/frustration,I avoid the person for some time,1,No,No,Often
44,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,4,Maybe,No,Often
45,I become quiet and withdraw,Feeling disrespected,I avoid the person for some time,3,Yes,Not applicable,Rarely
46,I become quiet and withdraw,Feeling ignored,I calm down quickly,3,Yes,Not applicable,Always
47,It depends,"Can't I pick two frustration, criticism, lies ...",I cry,3,Maybe,Not applicable,Sometimes
48,It depends,Dishonesty or lies,I regret some of my words,3,Maybe,Yes,Always
49,I say things impulsively,Being misunderstood and frustration,I avoid the person for some time,3,Maybe,Not applicable,Sometimes
50,I speak more emotionally/intensely,Feeling disrespected,I regret some of my words,4,Not applicable,Yes,Often
51,I avoid the conversation entirely,Being misunderstood,I avoid the person for some time,3,Yes,Not applicable,Often

In [159]:
def encode(df, column_name, categories):
    encoder = pp.OrdinalEncoder(categories=[categories], dtype=int)
    encoded = encoder.fit_transform(df[[column_name]])
    df[column_name] = encoded.astype(int)
    return df

encode(anger, 'Reflection', ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'])

anger['Reaction'] = anger['Reaction'].replace(
    'Be quiet and let them know Thier faults we reflect together after they are done talking then I tell them not to interrupt me when talking',
    'I stay quiet while they speak, reflect together afterward, address their faults, and ask them not to interrupt me when I speak.',
    regex=False
).str.strip()

encode(anger, 'Reaction', [
    'I become quiet and withdraw',
    'It depends',
    'I say things impulsively',
    'I avoid the conversation entirely',
    'I raise my voice',
    'I cry',
    'I speak more emotionally/intensely',
    'I try to explain my feelings calmly',
    'I stay quiet while they speak, reflect together afterward, address their faults, and ask them not to interrupt me when I speak.',
    "It depends on the person if he/she is raising their voice i will but if they aren't i wont"
])

encode(anger, 'Trigger', ['Feeling disrespected',
                          'Being misunderstood',
                          'Repetition/frustration',
                          'Dishonesty or lies',
                          'Feeling ignored',
                          'Criticism',
                          'Accusations',
                          'Feeling disrespected and being gaslit',
                          'Lies, criticism, betrayal',
                          'Disrespecting my parents',
                          'All except lies'
                          'Frustration, criticism, lies, being misunderstood',
                          'Being misunderstood and frustration'
                          ])

encode(anger, 'Handling', [
    'I apologise if necessary',
    'I reflect on what was said',
    'I avoid the person for some time',
    'I regret some of my words',
    'I calm down quickly',
    'Omoo',
    'I leave the scene to think things through',
    'I reflect on my actions, apologise when wrong, and calmly or humorously discuss both sides faults, recognising that we may each have some truth.'
    'I cry'
])

ValueError: Found unknown categories ['Be quiet and let them know Thier faults we reflect together after they are done talking then I tell them not to interrupt me when talking'] in column 0 during fit

In [ ]:
anger['Trigger'].value_counts()

Trigger
Feeling disrespected                                 16
Being misunderstood                                  13
Repetition/frustration                                7
Dishonesty or lies                                    5
Feeling ignored                                       3
Criticism                                             1
Accusations                                           1
Feeling disrespected and being gaslit                 1
Disrespecting my parents                              1
Lies, criticism, betrayal                             1
All except lies                                       1
Frustration, criticism, lies, being misunderstood     1
Being misunderstood and frustration                   1
Name: count, dtype: int64

In [ ]:
anger['Handling'].value_counts()

Handling
I apologise if necessary                                                                                                                            13
I reflect on what was said                                                                                                                          13
I avoid the person for some time                                                                                                                    12
I regret some of my words                                                                                                                            6
I calm down quickly                                                                                                                                  3
Omoo                                                                                                                                                 2
I leave the scene to think things through                                                                                                            1
I reflect on my actions, apologise when wrong, and calmly or humorously discuss both sides faults, recognising that we may each have some truth.     1
I cry                                                                                                                                                1
Name: count, dtype: int64

Our motive is to first understand how the `Reaction`, `Trigger`, `Meaning` and `Handling` work hand-in-hand to the anger communication pathway. They are all dependent on each other to find an independent variable which is still unknown.